import type { Metadata } from 'next'
import './globals.css'
import { GeistSans } from 'geist/font/sans'

interface Props {
	children: React.ReactNode
}

const Layout = ({ children }: Props) => {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={GeistSans.className}>{children}</body>
		</html>
	)
}

export default Layout

//→ metadata

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}
